### ISSUE TITLE
Scan not working properly

### ISSUE THREAD

**Issue by fg91** [wykvictor/cs344-udacity#1]
https://github.com/wykvictor/cs344-cuda-udacity/blob/c95af73c234bba1706242a7c542ccde6b24bf915/Problem%20Sets/Problem%20Set%203/student_func.cu#L167

Hey,
I realize you worked on this three years ago but maybe it still interests you :)

I think this line is problematic because threads might interfere with each other.

`sdata[myId] += sdata[myId - d];`

Consider `sdata[myId + d]`: it will add `sdata[myId]` to itself but the result depends on whether `sdata[myId - d]` was already added to `sdata[myId]`.

And indeed your code gives slightly different results (difference images) when run several times.

Maybe consider something like this instead:

```
__global__ void scanHillisSteele(int *d_out, int *d_in, int n) {
  int idx = threadIdx.x;
  extern __shared__ int temp[];
  int pout = 0, pin = 1;

  temp[idx] = (idx > 0) ? d_in[idx - 1] : 0;
  __syncthreads();

  for (int offset = 1; offset < n; offset *= 2) {
    // swap double buffer indices
    pout = 1 - pout;
    pin = 1 - pout;
    if (idx >= offset) {
      temp[pout*n+idx] = temp[pin*n+idx - offset] + temp[pin*n+idx];  // changed line
    } else {
      temp[pout*n+idx] = temp[pin*n+idx];
    }
    __syncthreads();
  }
  d_out[idx] = temp[pout*n+idx];
}
```

Best regards :)

Fabio

**Comment by wykvictor** [comment]
Thanks a lot for pointing out the problem.
Yes, we should use double buffer to avoid interfere between threads. I will update the code accordingly. Welcome to leave a message if other issues found in this repo.
